# SWISTART
# The source files in this folder are copied from /sierra
# during build process, see linux_quic-git.bb.
obj-$(CONFIG_SIERRA) += sierra_smem.o bcmsg_kernel.o bcmsg_utils.o sierra_smem_msg.o
# SWISTOP
